"""Agregar tabla system_settings

Revision ID: 1ce8ec34dc08
Revises: e6eb11a14d59
Create Date: 2026-01-27 02:28:49.270262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce8ec34dc08'
down_revision: Union[str, Sequence[str], None] = 'e6eb11a14d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
