"""Agregar tablas scheduler Celery

Revision ID: 83508930d627
Revises: bd8343af72e4
Create Date: 2026-01-27 14:02:22.273318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '83508930d627'
down_revision: Union[str, Sequence[str], None] = 'bd8343af72e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('celery_periodic_task')
    op.drop_table('celery_interval_schedule')
    op.drop_table('celery_crontab_schedule')
    op.drop_table('celery_solar_schedule')
    op.drop_table('celery_periodic_task_changed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_periodic_task_changed',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('last_update', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_periodic_task_changed_pkey'))
    )
    op.create_table('celery_solar_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_solar_schedule_pkey'))
    )
    op.create_table('celery_crontab_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minute', sa.VARCHAR(length=240), autoincrement=False, nullable=True),
    sa.Column('hour', sa.VARCHAR(length=96), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('day_of_month', sa.VARCHAR(length=124), autoincrement=False, nullable=True),
    sa.Column('month_of_year', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_crontab_schedule_pkey'))
    )
    op.create_table('celery_interval_schedule',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('every', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', sa.VARCHAR(length=24), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_interval_schedule_pkey'))
    )
    op.create_table('celery_periodic_task',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('task', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('interval_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crontab_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('solar_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('args', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kwargs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('queue', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('routing_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expires', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('one_off', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('total_run_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date_changed', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('celery_periodic_task_pkey')),
    sa.UniqueConstraint('name', name=op.f('celery_periodic_task_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
