"""Agregar tabla system_settings

Revision ID: a0652d9955d7
Revises: 1ce8ec34dc08
Create Date: 2026-01-27 02:39:45.495067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0652d9955d7'
down_revision: Union[str, Sequence[str], None] = '1ce8ec34dc08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
